#!/bin/bash
#PBS -N ge1.4_test_TheCOUP
#PBS -j oe
##PBS -l feature=haswell
#PBS -l nodes=21:ppn=24
#PBS -q large
#PBS -A NRELMatDB
#PBS -l walltime=03:00:00

cd /scratch/felixt/PhononCode/runs/ge1/

PHONPATH=/scratch/felixt/PhononCode

cp PHONON.out $(mktemp -u PHONON.old.XXXXX)

#mpirun -np 501 python3 $PHONPATH/PhononCode.py -n 1000 -E 2600 -w 0.001 -o ge1.4_0 > ge1.4_0.log

for s in 1
do
    for i in 0 $(seq 20)
    do
        for ve in 0.1 0.5 2 10
	do
	    vs=$(echo "${ve}/2" | bc -l)
            if [ $i == "0" ]
		    then
		c="0.001"
		    else
		        c=$(echo "0.005*${i}" | bc -l)
	    fi
            mpirun -np 501 python3 $PHONPATH/PhononCode.py -n 1000 -E 2600 -w 0.001 -d -t random -v [[${ve},${ve}],${vs}] -m [1] -c ${c} -r 5 -o ge1.4_${c}-${ve} > ge1.4_${c}-${ve}.log
        done
        echo -e "" >> PHONON.out
    done
done