#!/bin/bash
#PBS -N TheCOUP
#PBS -j oe
##PBS -l feature=haswell
#PBS -l nodes=21:ppn=24
#PBS -q large
#PBS -A NRELMatDB
#PBS -l walltime=24:00:00

cd /scratch/felixt/PhononCode/secondrun

mv PHONON.out PHONON.out.old

# mpirun -np 101 python3 PhononCode.py -n 200 -w 0.02 -o run_0
for s in 1
do
    for i in 0 $(seq 20)
    do
        for ve in 2 3
	do
	    vs=$(echo "${ve}/2" | bc -l)
            if [ $i == "0" ]
		    then
		c="0.001"
		    else
		        c=$(echo "0.005*${i}" | bc -l)
	    fi
            mpirun -np 501 python3 ../PhononCode.py -n 1000 -E 500 -w 0.003 -d -t random -v [[${ve},${ve}],${vs}] -m [1] -c ${c} -r 5 -o potential_runs_${c}-${ve} > potential_runs_${c}-${ve}.log
        done
        echo -e "" >> PHONON.out
    done
done